# Generated by Django 4.2.8 on 2024-03-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CloudCredential',
            new_name='ModelsCredentials',
        ),
    ]
