# Generated by Django 4.2.8 on 2024-03-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_rename_cloudcredential_modelscredentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key_id', models.CharField(help_text='AWS Access Key ID', max_length=100)),
                ('secret_access_key', models.CharField(help_text='AWS Secret Access Key', max_length=100)),
                ('role_arn', models.CharField(blank=True, help_text='Role ARN for cross-account access', max_length=2048, null=True)),
                ('session_name', models.CharField(blank=True, help_text='Session name for assuming the role', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AzureCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='Azure Client ID', max_length=100)),
                ('client_secret', models.CharField(help_text='Azure Client Secret', max_length=100)),
                ('tenant_id', models.CharField(help_text='Azure Tenant ID', max_length=100)),
                ('subscription_id', models.CharField(help_text='Azure Subscription ID', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChatGPTCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='ChatGPT API Key', max_length=255)),
                ('description', models.CharField(blank=True, help_text='Description or purpose of the API key', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GCPCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the GCP service account', max_length=100)),
                ('credential_file', models.FileField(help_text='GCP JSON key file', upload_to='gcp_credentials/')),
            ],
        ),
        migrations.DeleteModel(
            name='ModelsCredentials',
        ),
    ]
