# concurrent connection for workers
concurrent_max_workers: 3
git_aws_compliance_dir: /tmp/steampipe-mod-aws-compliance/
git_gcp_compliance_dir: /tmp/steampipe-mod-gcp-compliance/
git_azure_compliance_dir: /tmp/steampipe-mod-azure-compliance/
# /home/iaws is path in docker
dynamic_form: /home/iaws/dynamic_form.yaml
dashbord: /home/iaws/dashboard.yaml
cache_timeout: 3000
STEAMPIPE_CACHE: true
STEAMPIPE_CACHE_TTL: 60
STEAMPIPE_MOD_LOCATION: ~/my-steampipe-mods

