table_path: ["/table/aws_ec2_instance/","/table/aws_ec2_ami/","/table/aws_ec2_*","/compliance_report_by_servicename/AWS/S3/"]
form_heading: "New EC2 Instances To Be Created second option"
default_region: us-west-2
command_to_run: "terraform"
resources:
  - type: ec2_instance
    properties:
      instance_type: 
        type: "select"
        options: ["t2.micro", "t2.small", "t2.medium"]
        required: true
        help_text: "Select instance type"
      memory: 
        type: "input"
        default: "4GB"
        required: false
      enable_monitoring: 
        type: "boolean"
        required: true
      launch_date: 
        type: "date"
        required: false
      description: 
        type: "textarea"
        required: true
        regex: "^[\\w\\s]{5,10}$"  # Regex for min 5, max 10 words
---
table_path: ["/table/aws_ec2_instance/","/compliance_report_by_servicename/AWS/S3/","/compliance_report_by_servicename/AWS/Account/"]
form_heading: "Delete EC2 Instances"
default_region: us-west-2
command_to_run: "terraform"
resources:
  - type: ec2_instance
    properties:
      instance_type:
        type: "select"
        options: ["t2.micro", "t2.small", "t2.medium"]
        required: true
        help_text: "Select instance type"
---
table_path: ["aws_s3_bucket"]
form_heading: "Create new S3 bucket"
default_region: us-west-2
command_to_run: "terraform"
resources:
  - type: s3_bucket
    properties:
      Bucket Name:
        type: "input"
        required: true
        help_text: "Write name of the bucket"
---
table_path: ["aws_s3_bucket"]
form_heading: "Remove S3 bucket"
default_region: us-west-2
command_to_run: "terraform"
resources:
  - type: s3_bucket
    properties:
      Bucket Name:
        type: "input"
        required: true
        help_text: "write s3 bucket name"
---
table_path: ["aws_s3_bucket"]
form_heading: "Copy to GCP Storage"
default_region: us-west-2
command_to_run: "terraform"
resources:
  - type: s3_bucket
    properties:
      Bucket Name:
        type: "input"
        required: true
        help_text: "write s3 bucket name"
---
table_path: ["aws_s3_bucket"]
form_heading: "Set Bucket Encryption in All S3 Buckets"
default_region: us-west-2
command_to_run: "/home/japjot/linux/config/iaws/custom_scripts/s3_bucket_encryption.sh"
resources:
  - type: s3_bucket
    properties:
      Bucket Name:
        help_text: "write s3 bucket name"
---
table_path: ["/compliance_report_by_servicename/AWS/Account/"]
form_heading: "Create Account report "
default_region: us-west-2
command_to_run: "date"
resources:
  - type: ec2_instance
    properties:
      instance_type:
        type: "select"
        options: ["t2.micro", "t2.small", "t2.medium"]
        required: true
        help_text: "Select instances type"
---
table_path: ["aws_eks_cluster"]
form_heading: "Create EKS "
default_region: us-west-2
command_to_run: "/home/japjot/linux/config/iaws/custom_scripts/create_eks.sh"
resources:
  - type: eks_cluster
    properties:
      Name:
        type: "input"
        required: true
        regex: "^[\\w\\s]{5,10}$"  # Regex for min 5, max 10 words
      Description:
        type: "textarea"
        required: true
        regex: "^[\\w\\s]{5,10}$"  # Regex for min 5, max 10 words
---
table_path: ["aws_eks_cluster"]
form_heading: "Remove EKS "
default_region: us-west-2
command_to_run: "/home/japjot/linux/config/iaws/custom_scripts/remove_eks.sh"
resources:
  - type: ec2_instance
    properties:
      Name:
        type: "input"
        required: true
        regex: "^[\\w\\s]{5,10}$"  # Regex for min 5, max 10 words
      Description:
        type: "textarea"
        required: true
        regex: "^[\\w\\s]{5,10}$"  # Regex for min 5, max 10 words

---
table_path: ["aws_eks_cluster"]
form_heading: "Duplicate EKS "
default_region: us-west-2
command_to_run: "date"
resources:
  - type: ec2_instance
    properties:
      instance_type:
        type: "select"
        options: ["t2.micro", "t2.small", "t2.medium"]
        required: true
        help_text: "Select instances type"
      RDS:
        type: "textarea"
        required: true
        regex: "^[\\w\\s]{5,10}$"  # Regex for min 5, max 10 words
      description:
        type: "textarea"
        required: true
        regex: "^[\\w\\s]{5,10}$"  # Regex for min 5, max 10 words
