# Generated by Django 4.2.8 on 2024-02-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskresult',
            name='status',
            field=models.CharField(default='Success', max_length=100),
        ),
    ]
