# Generated by Django 4.2.8 on 2024-02-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_taskresult_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='script',
            field=models.FileField(blank=True, upload_to='scripts/'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='shell',
            field=models.CharField(blank=True, choices=[('bash', 'Bash'), ('tcsh', 'Tcsh')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='command',
            field=models.TextField(blank=True),
        ),
    ]
