# Generated by Django 4.2.8 on 2024-04-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_scheduledtask_script_scheduledtask_shell_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
